export enum SocketEvent {
    LOGS = 'LOGS',
    CONNECT_TO_SERVER = 'CONNECT_TO_SERVER',
    DISCONNECT_FROM_SERVER = 'DISCONNECT_FROM_SERVER',
    CONNECTED = 'CONNECTED',
    DISCONNECTED = 'DISCONNECTED',
    SERVER_LOG = 'SERVER_LOG',
    START_SERVER = 'START_SERVER',
    STOP_SERVER = 'STOP_SERVER',
    SERVER_STARTED = 'SERVER_STARTED',
    SERVER_STOPPED = 'SERVER_STOPPED',
    EXECUTE_COMMAND = 'EXECUTE_COMMAND',
    COMMAND_EXECUTED = 'COMMAND_EXECUTED',
}

export default SocketEvent